### ISSUE TITLE
عدم التعرف على الملفات ؟

### ISSUE THREAD

**Issue by xiperfect** [nakhla/subscene-subtitle-rightclick-downloader#1]
تقريبا كل العناصر الي جربتها يطلع لي " لا يمكن العثور عليها "

![image](https://user-images.githubusercontent.com/124534657/216849518-9c0e1592-c5fc-4465-adb4-472dc25cc125.png)

**Comment by nakhla** [comment]
للأسف موقع subscene عمل تعديل في الواجهة وأصبح يستخدم cloudflare لحماية ملفات الترجمة وتمنع استخدام أي web scraping technology مما أثر تأثير مباشر على الكود الخاص بنا وجعله لا يعمل بالشكل المطلوب...

**Comment by xiperfect** [comment]
شي مؤسف الصراحة ، كانت بتريحنا هالحركة ، يعطيك العافية على مجهودك ، تعبناك معنا ...

**Comment by nakhla** [comment]
> شي مؤسف الصراحة ، كانت بتريحنا هالحركة ، يعطيك العافية على مجهودك ، تعبناك معنا ...
تم تعديل الكود والآن يعمل بشكل جيد.. اذا اردت التجربة عليك بتحميل الملفات الجديدة وتثبيته من البداية كما في الوصف

**Comment by nakhla** [comment]
تم تعديل الكود والآن يعمل بشكل جيد.. اذا اردت التجربة عليك بتحميل الملفات الجديدة وتثبيته من البداية كما في الوصف

**Comment by xiperfect** [comment]
تم التجربة ويعمل بشكل ممتاز ، شكرًا جزيلًا لك على جهودكم الحثيثة بالتطوير.

‫في الأحد، 7 مايو 2023 في 1:28 ص تمت كتابة ما يلي بواسطة ‪nakhla‬‏ <‪
***@***.***‬‏>:‬
